### ISSUE TITLE
Compile emits a "else" clauses will never match warning

### ISSUE THREAD

**Issue by leseigneur** [membraneframework/bunch#29]
I don't know if it is a compiler issue or a macro issue.
With the code belong, compiler emits this warning : warning: "else" clauses will never match because all patterns in "with" will always match.
The code works well and the warning is wrong : else clauses do get called eventually.

Here is the code:
```elixir
def compute_home_vars(params, socket) do
    withl connected: true <- connected?(socket),
          world_id_str: {:ok, world_id_str} <- Map.fetch(params, "world_id"),
          world_id: world_id <- String.to_integer(world_id_str),
          world: {:ok, world} <- Msim.Simulator.get_world_db(world_id, true),
          path: true <- check_path_to_module(__MODULE__, world.type.front_module),
          banks: {:ok, banks} <- World_A.call_cmd(world_id, {:list_banks, []}) do
      # normal case
      Logger.debug("connected")
      {world_id, world, true, banks}
    else
      connected: _ ->
        Logger.debug("not connected")
        {nil, nil, false, nil}
      world_id_str: _ ->
        {nil, nil, false, nil}
      world_id: _ ->
        {nil, nil, false, nil}
      world: _ ->
        {world_id, nil, false, nil}
      path: _ ->
        {world_id, world, false, nil}
      banks: _ ->
        {world_id, world, true, nil}
    end
  end
```

**Comment by mat-hek** [comment]
Hi @leseigneur , I took the freedom to format your code ;) The warning should contain the exact line  where the problem occurs:
> warning: "else" clauses will never match because all patterns in "with" will always match
  iex:5

and it's this one:

```elixir
world_id: world_id <- String.to_integer(world_id_str),
```

`world_id` matches everything, so the corresponding `else` clause will never match. BTW, the compiler can detect that because you use `withl` ;)

**Comment by leseigneur** [comment]
Thank you for the formatting. I'd like to learn how not to loose the format whenever I paste it into github.
Unfortunately the compile points to the withl line, not to the actual world_id: line
Thanks a lot for the analysis, I'll turn my <- into a proper assign then.

**Comment by mat-hek** [comment]
To preserve the formatting just type
\```elixir
your_code
\```

IEx misled me about the line number, I'll check if it can be more accurate
